### ISSUE TITLE
TDM how to load trained weight for continue train

### ISSUE THREAD

**Issue by zdx3578** [vitchyr/rlkit#4]
how to play trained weight, show render  result;

**Comment by vitchyr** [comment]
Thanks for pointing this out. You're right--`sim_policy` won't work with TDM policies/envs. You can use [multitask_rollout](https://github.com/vitchyr/rlkit/blob/master/rlkit/torch/tdm/sampling.py#L43).

Basically, rather than doing
```
path = rollout(
    env,
    policy,
    max_path_length=args.H,
    animated=True,
)
```
as in `sim_policy.py` do
```
goal = env.sample_goal_for_rollout()
path = multitask_rollout(
    env,
    policy,
    init_tau=max_tau,
    goal=goal,
    max_path_length=args.H,
    animated=True,
    decrement_tau=True,
    cycle_tau=True,
)
```

I'll add an explicit script for this soon.

**Comment by vitchyr** [comment]
See 5b36878e647b66f82d3e8e94e57546708fb2ed4d
