### ISSUE TITLE
AttributeError: attribute 'site_pos' of 'mujoco_py.cymj.PyMjModel' objects is not writable

### ISSUE THREAD

**Issue by jiameij** [vitchyr/rlkit#5]
thanks for your share !
i have a question:
when i run examples/tdm/ant_position.py, it returns:
`2018-05-14 08:29:57.628702 CST | Variant:
2018-05-14 08:29:57.628908 CST | {
  "algorithm": "TDM",
  "tdm_kwargs": {
    "reward_scale": 10,
    "discount": 1,
    "max_path_length": 50,
    "batch_size": 128,
    "num_pretrain_paths": 0,
    "num_epochs": 500,
    "num_steps_per_epoch": 1000,
    "num_steps_per_eval": 1000,
    "tau": 0.001,
    "num_updates_per_env_step": 5,
    "max_tau": 49
  }
}
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "/home/jiamj/rlkit/examples/tdm/ant_position.py", line 87, in <module>
    experiment(variant)
  File "/home/jiamj/rlkit/examples/tdm/ant_position.py", line 15, in experiment
    env = NormalizedBoxEnv(GoalXYPosAnt(max_distance=6))
  File "/home/jiamj/rlkit/rlkit/torch/tdm/envs/ant_env.py", line 21, in __init__
    self.set_goal(np.array([self.max_distance, self.max_distance]))
  File "/home/jiamj/rlkit/rlkit/torch/tdm/envs/ant_env.py", line 41, in set_goal
    self.model.site_pos = site_pos
AttributeError: attribute 'site_pos' of 'mujoco_py.cymj.PyMjModel' objects is not writable`
how can i solve it?
thanks again!

**Comment by vitchyr** [comment]
Good catch. This is because that env was written assuming Mujoco 1.3/mujoco-py 0.5.7/gym 0.9.6

I recently update things to Mujoco 1.5/mujoco-py 1.3/gym 0.10.5, but I probably forgot to update these environments. There's a few things need to port over the env (e.g. `self.model.data` becomes `self.data`, `def _step` becomes `def step`). I'll get to this after the NIPS deadline, but in the meantime you're welcome to make a PR.

By the way, based on your error though it looks like you might have a mix of gym 0.10.5 and mujoco-py 0.5.7, which is probably not a good idea. The new mujoco-py has that attribute.

**Comment by jiameij** [comment]
thank you for your prompt reply.
i will update my environment and try to make a PR
Good luck with your paper!

**Comment by vitchyr** [comment]
See 495d0855d91664bc74ae597d1e1c1483d6b28f4c
