### ISSUE TITLE
distance in code ???

### ISSUE THREAD

**Issue by kimchicanh** [vitchyr/rlkit#76]
Hi,

I am a little bit confused with your distance:
![image](https://user-images.githubusercontent.com/20283416/63247677-d1f33680-c28f-11e9-8056-3e2dc90cd03c.png)
You calculate reward twice ???
What is the benefit of the first calculate ???

Thanks

**Comment by vitchyr** [comment]
Correct. We replace the "ground truth" reward from the environment with the latent reward. In simulation it's easy to get the ground truth reward, but not for (e.g.) real-world robot tasks, at which point the reward returned by the wrapped_env is meaningless. Also, it's usually not that expensive to compute the ground truth reward, so the overhead shouldn't be large.

In the future, it would help to [link to the code](https://help.github.com/en/articles/creating-a-permanent-link-to-a-code-snippet) rather than taking a screenshot.
